[package]
name    = "browser"
version = "0.0.1"
edition = "2021"

description = "Interactive Media Engine: WASM/browser player"
authors     = ["Dmitry Ponyatov <dponyatov@gmail.com>"]
license     = "MIT"

[dependencies]
lib = { path = "../lib" }
