#!/bin/sh
#
# https://wiki.inmys.ru/doku.php?id=boards:nms-hh-px30:autorun

. /etc/profile

case "$1" in
  start)
		weston --tty=5 --idle-time=0 &
		{
			# Wait for weston ready
			# while [ ! -e ${XDG_RUNTIME_DIR}/wayland-0 ]; do
			# 	sleep .1
			# done
            echo "Wayland!" ${XDG_RUNTIME_DIR}
            ls -la ${XDG_RUNTIME_DIR}
            # weston-terminal
		}&
    ;;
  stop)
		killall weston-terminal
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
